services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # .env から各変数を読み込む記述に変更Docker Compose 自体も標準で .env ファイルを読み込む機能を備えている
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # ports:    ← Docker内で起動中のDBとWebサーバーの通信となるので、へたにDocker外にポートをさらさないこと
    #   - "5432:5432"

  web:
    build: .  # 同じフォルダにあるDockerfileを使う
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # ローカルの変更を即座に反映させる（ボリュームマウント）
    ports:
      - "8081:8000"
    depends_on:
      - db

volumes:
  postgres_data: